export { roundMessageTemplate } from './templates/round-template'
export { auditMessageTemplate } from './templates/audit-template'
export { a0 } from './teams/a0'
export { a1 } from './teams/a1'
export { crucible } from './teams/crucible'
export { sparring } from './teams/sparring'
export { warRoom } from './teams/war-room'
export { brokeredTrio } from './teams/brokered-trio'
