export { AIACanvas, type AIACanvasRef } from './aia-canvas'
export { AIAgent, type AIAgentProps } from './aia-agent'
export { AIASphere } from './aia-sphere'
export { useAIASphere } from './useAIASphere'
export { AIARing } from './aia-ring'
export { useAIAContext, type AIAContextValue, type CanvasPhase } from './aia-context'
export type { BgVariant, BgRenderer, BgState, BgEvent } from './bg'
