#!/usr/bin/env bun
/**
 * Upgrades every `@attalabs/vinaya`-family package pin in this monorepo to
 * one target version, then regenerates and re-verifies everything that pin
 * feeds — the CI workflows and husky hooks Vinaya manages, and a clean
 * install to catch a stale nested duplicate.
 *
 * Exists because a plain `bun add @attalabs/vinaya@latest` misses three real
 * things, each found by hand while upgrading past `0.17.1` (`#970`, `#971`):
 *
 * 1. `apps/vinaya-portal/web` and `apps/vinaya-studio/web` pin `aeg-core`,
 *    `aeg-forge-state`, and (Portal only) `vinaya-sources` independently of
 *    the root `package.json` — a root-only bump silently leaves these on a
 *    stale range.
 * 2. `.github/workflows/vinaya-*.yml` and `.husky/pre-commit`/`pre-push`
 *    pin the version as a literal `npx --yes @attalabs/vinaya@<version>`
 *    string, generated by `vinaya init` and regenerated by `vinaya upgrade`
 *    — entirely separate from any `package.json`. A dependency bump with no
 *    `vinaya upgrade` leaves Ring 0 (hooks) and Ring 1 (CI) running the OLD
 *    version's checks while `package.json` claims the new one.
 * 3. A bump-in-place `bun install` can leave a stale nested
 *    `node_modules/@attalabs/<pkg>/node_modules/@attalabs/aeg-types` copy at
 *    the OLD version sitting alongside the newly-hoisted one — invisible
 *    until TypeScript reports two structurally-incompatible copies of the
 *    same exported type. A clean reinstall is the only reliable fix found.
 *
 * This script does the mechanical part only. It does not commit, push, or
 * open a PR — read its final report and finish the task the normal way:
 * fix whatever `typecheck`/`doctor` still flags (most commonly a
 * `doc-coverage` pointer under `apps/vinaya-portal/**`/`apps/vinaya-studio/**`
 * — see this skill's own note below on why that doc commit must land BEFORE
 * the dependency-bump commit, not after or in the same one), verify with
 * `bun run check`, then commit and open the PR yourself.
 *
 * Usage: `bun scripts/upgrade-vinaya.ts [version]` — omit `version` to
 * resolve the latest published `@attalabs/vinaya` from npm.
 */

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const REPO_ROOT = join(import.meta.dir, '..')
const VINAYA_PACKAGES = [
  '@attalabs/vinaya',
  '@attalabs/aeg-core',
  '@attalabs/aeg-forge-state',
  '@attalabs/aeg-types',
  '@attalabs/vinaya-sources'
] as const

function sh(cmd: string, args: string[], opts: { cwd?: string } = {}): string {
  return execFileSync(cmd, args, { cwd: opts.cwd ?? REPO_ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] })
}

function shInherit(cmd: string, args: string[], opts: { cwd?: string } = {}): void {
  execFileSync(cmd, args, { cwd: opts.cwd ?? REPO_ROOT, encoding: 'utf8', stdio: 'inherit' })
}

/** Every `package.json` in the tree, excluding `node_modules` and worktrees — a plain recursive walk, this repo has no workspace glob library dependency-free enough to reuse here. */
function findPackageJsonFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (
      entry.name === 'node_modules' ||
      entry.name === '.git' ||
      entry.name === '.worktrees' ||
      entry.name === '.next' ||
      entry.name === '.turbo'
    )
      continue
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      findPackageJsonFiles(full, out)
    } else if (entry.name === 'package.json') {
      out.push(full)
    }
  }
  return out
}

/** Preserves whatever range prefix (`^`, or none for an exact pin) the existing value already used — this repo mixes both conventions across files and neither is this script's call to change. */
function bumpedRange(existing: string, targetVersion: string): string {
  return existing.startsWith('^') ? `^${targetVersion}` : targetVersion
}

function resolveTargetVersion(argVersion: string | undefined): string {
  if (argVersion) return argVersion
  return sh('npm', ['view', '@attalabs/vinaya', 'version']).trim()
}

function bumpPackageJson(path: string, targetVersion: string): string[] {
  const raw = readFileSync(path, 'utf8')
  const pkg = JSON.parse(raw) as { dependencies?: Record<string, string>; devDependencies?: Record<string, string> }
  const changed: string[] = []
  for (const section of ['dependencies', 'devDependencies'] as const) {
    const deps = pkg[section]
    if (!deps) continue
    for (const name of VINAYA_PACKAGES) {
      const existing = deps[name]
      if (existing === undefined) continue
      const next = bumpedRange(existing, targetVersion)
      if (next !== existing) {
        deps[name] = next
        changed.push(`${name}: ${existing} -> ${next}`)
      }
    }
  }
  if (changed.length > 0) {
    // Preserve key order and formatting style (2-space indent, trailing newline) — a
    // `JSON.stringify` round-trip through the parsed object already matches this
    // repo's existing package.json formatting (verified against biome's own
    // formatter output for these files at the time this script was written).
    writeFileSync(path, `${JSON.stringify(pkg, null, 2)}\n`)
  }
  return changed
}

async function main() {
  const targetVersion = resolveTargetVersion(process.argv[2])
  console.log(`\n[upgrade-vinaya] target version: ${targetVersion}\n`)

  const packageJsonFiles = findPackageJsonFiles(REPO_ROOT)
  const bumped: Array<{ path: string; changes: string[] }> = []
  for (const path of packageJsonFiles) {
    const changes = bumpPackageJson(path, targetVersion)
    if (changes.length > 0) bumped.push({ path: path.replace(`${REPO_ROOT}/`, ''), changes })
  }

  if (bumped.length === 0) {
    console.log(
      '[upgrade-vinaya] no package.json declared any @attalabs/vinaya-family package below the target version — nothing to bump.'
    )
  } else {
    console.log('[upgrade-vinaya] bumped:')
    for (const { path, changes } of bumped) {
      console.log(`  ${path}`)
      for (const c of changes) console.log(`    ${c}`)
    }
  }

  console.log('\n[upgrade-vinaya] bun install (resolve the bump)...')
  shInherit('bun', ['install'])

  console.log(
    `\n[upgrade-vinaya] npx --yes @attalabs/vinaya@${targetVersion} upgrade --yes (regenerate CI workflows + hooks)...`
  )
  shInherit('npx', ['--yes', `@attalabs/vinaya@${targetVersion}`, 'upgrade', '--yes'])

  console.log('\n[upgrade-vinaya] clean reinstall (flush any stale nested duplicate)...')
  const nodeModulesDirs = [
    join(REPO_ROOT, 'node_modules'),
    ...readdirSync(join(REPO_ROOT, 'apps'), { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .flatMap((e) => {
        const webDir = join(REPO_ROOT, 'apps', e.name, 'web', 'node_modules')
        return existsSync(webDir) ? [webDir] : []
      })
  ]
  shInherit('rm', ['-rf', ...nodeModulesDirs])
  shInherit('bun', ['install'])

  console.log('\n[upgrade-vinaya] bunx turbo typecheck --force...')
  let typecheckOk = true
  try {
    shInherit('bunx', ['turbo', 'typecheck', '--force'])
  } catch {
    typecheckOk = false
  }

  console.log(`\n[upgrade-vinaya] npx --yes @attalabs/vinaya@${targetVersion} doctor...`)
  let doctorOutput = ''
  try {
    doctorOutput = sh('npx', ['--yes', `@attalabs/vinaya@${targetVersion}`, 'doctor'])
    console.log(doctorOutput)
  } catch (e) {
    doctorOutput = String((e as { stdout?: string }).stdout ?? e)
    console.log(doctorOutput)
  }

  console.log('\n[upgrade-vinaya] ── report ──────────────────────────────────────')
  console.log(`Target version: ${targetVersion}`)
  console.log(`Files bumped: ${bumped.length}`)
  console.log(`Typecheck: ${typecheckOk ? 'PASS' : 'FAIL — read the output above before doing anything else'}`)
  const drifted = doctorOutput.split('\n').filter((l) => l.includes('⚠') || l.includes('✗'))
  if (drifted.length > 0) {
    console.log(`doctor flagged ${drifted.length} item(s) — read each one; most commonly a doc-coverage pointer under`)
    console.log('apps/vinaya-portal/** or apps/vinaya-studio/**. If so: commit that doc fix as its OWN commit')
    console.log("BEFORE committing this dependency bump, not after and not combined — doc-coverage's local")
    console.log('pre-commit check diffs only committed history (main...HEAD), never staged-but-uncommitted')
    console.log('content, so it only resolves in the order docs-then-code.')
  } else {
    console.log('doctor: no drift.')
  }
  console.log('\nNext: run `bun run check` for the full sweep, fix anything doctor/typecheck flagged (docs before')
  console.log('code if a doc-coverage pointer applies), then commit and open the PR yourself — this script does')
  console.log('not do either.')
}

main()
